Add API functionality
OscarFMdev/bookstore pull request #4
Opened 2022-11-10 19:42 UTC by OscarFMdev

# PR description:
In this branch I:
- Configured store to use API data. 🗳️ 
- Implemented Add and remove functionality for books. 📖 
- Added Axios and API functions for adding, fetching, and deleting books. 📚 

#### Thank you for reviewing my code! 🙌🏽

2022-11-10 20:02 UTC, mmsesay requested changes
Hi @OscarFMdev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title :heavy_check_mark: 
 - Good PR summary :heavy_check_mark:  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-10 20:02 UTC, mmsesay commented on src/API/bookstoreAPI.js
> +};
- [ ] It is required that students make use of [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk). This will make it easier for your action creators to dispatch the lifecycle actions based on the returned promise. 

Please apply the same changes to `addBookAPI` and `deleteBookAPI` functions as well.

Finally, do not forget to `import { createAsyncThunk } from '@reduxjs/toolkit';` so that you won't encountercreateAsyncThunk not defined error.

Example:
```js
export const fetchBooksAPI = createAsyncThunk(
  'books/GET_BOOKS',
  async () => {
    const response = await axios.get(APP_URL);
    return response.data;
  },
); 
```

2022-11-10 20:09 UTC, OscarFMdev commented on src/API/bookstoreAPI.js
> +};
Thank you @mmsesay for helping me improve my code, I'll fix it! 🙌🏽

2022-11-10 22:33 UTC, Munsa1 requested changes
Hi @OscarFMdev, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make the required changes which was requested by the previous reviewer, you did not make any commits after the first review
![image](https://user-images.githubusercontent.com/81932478/201220181-6f977c40-8783-44e5-a813-d386b13670ab.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 00:04 UTC, peterrobert approved these changes
Hi @OscarFMdev , 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 00:19 UTC, OscarFMdev commented
Thank you @peterrobert !

2022-11-11 00:19 UTC, merged